; PlatformIO Project Configuration File - Kit Helio
; ===================================================
; Sub-projeto Kit Helio (Gateway e Nós)

[platformio]
default_envs = d1_mini_kit_helio_gateway

; =======================================================
; ENV: GATEWAY KIT HELIO (ESP8266 D1 Mini)
; =======================================================
[env:d1_mini_kit_helio_gateway]
extends = common
platform = espressif8266@2.6.3
board = d1_mini
framework = arduino
build_src_filter =
    +<src/DRY/kit-helio/gateway/libDryGatewayMqtt.cpp>

monitor_port = COM5
upload_port = COM5
upload_speed = 115200
monitor_speed = ${common.monitor_speed}

board_build.filesystem = littlefs
upload_resetmethod = nodemcu
upload_flags =
    --before=default_reset
    --after=hard_reset

lib_deps =
    mysensors/MySensors@^2.3.2
    bblanchon/ArduinoJson@^6.21.3
    knolleary/PubSubClient@^2.8

build_flags =
    ${common.flags}
    -D MQTT_MAX_PACKET_SIZE=512
    -D MY_NODE_ID=0
    -D MY_TRANSPORT_WAIT_READY_MS=1
    -D MY_GATEWAY_FEATURE
    -D MY_RF24_CE_PIN=2
    -D MY_RF24_CSN_PIN=15
    -D MY_TRANSPORT_DISCOVERY_TIMEOUT=60000
    -D MY_TRANSPORT_SANITY_CHECK_INTERVAL_MS=30000
    -D MY_OTA_LOG_SENDER_FEATURE
    -D M360_NATIVE_MQTT=1

; =======================================================
; ENV: NÓ SENSOR MINI DHT11 (Arduino Pro Mini 5V/16MHz)
; =======================================================
[env:pro16MHz_miniDHT]
extends = common
platform = atmelavr
board = pro16MHzatmega328
framework = arduino

build_src_filter =
    +<src/DRY/kit-helio/nos/miniDHT/>

monitor_speed = ${common.monitor_speed}

lib_deps =
    mysensors/MySensors@^2.3.2
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14

build_flags =
    ${common.flags}
    -D MY_NODE_ID=11
    -D MY_RF24_CE_PIN=9
    -D MY_RF24_CSN_PIN=10
    -D MY_DEBUG
    -D MY_RSSI_LOG_INTERVAL=30000
    -Isrc/DRY/kit-helio/nos/miniDHT


