; PlatformIO Project Configuration File - Kit Helio
; ===================================================
; Sub-projeto Kit Helio (Gateway e Nós)

[platformio]
src_dir = .
lib_dir = ../../../lib
include_dir = ../../../include

; Adicione aqui os [env:...] específicos do Kit Helio conforme o desenvolvimento
